[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "rust-pixi-template"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"
clean = "cargo clean"
test = "cargo test"
fmt = "cargo fmt"
lint = { cmd = "cargo clippy", depends-on = ["fmt"] }
lint-ci = { cmd = "cargo clippy" } # only for CI/CD
lint-fix = { cmd = "cargo clippy --fix --allow-dirty", depends-on = ["fmt"] }
doc = "cargo doc"
doc-open = "cargo doc --open"

[dependencies]
rust = ">=1.93.1,<1.94"
